### PR TITLE
Fix lint errors

### LINKED ISSUE #176: Fix lint errors
## Background

After installing the latest `ember-template-lint` and `eslint` in #173, I suppressed new lint errors by adding exceptions to rules:

- [.eslintrc.js](https://github.com/ember-learn/ember-help-wanted/blob/747d54e1431cfb58fd85cff4fef62035d96686b3/.eslintrc.js#L23-L27)
- [.template-lintrc.js](https://github.com/ember-learn/ember-help-wanted/blob/919ee6af2d79ca55b76c9ef065b97c43493c6612/.template-lintrc.js#L5-L18)

## TODOs

- [ ] Remove the rule exceptions in `.eslintrc.js` one by one. If there's a fix that can be done easily (with respect to time and low risk of breaking the app), please do so.

- [ ] Remove the rule exceptions in `.template-lintrc.js` one by one. If there's a fix that can be done easily (with respect to time and low risk of breaking the app), please do so.

In general, you may want to check if there is a codemod that you can run. Because this app is relatively small, it may be better to manually fix the errors.

### eslint-plugin-ember

- [no-get](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-get.md)
- [require-computed-macros](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-computed-macros.md)
- [use-ember-data-rfc-395-imports](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/use-ember-data-rfc-395-imports.md)

### ember-template-lint

- [link-rel-noopener](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/link-rel-noopener.md)
- [no-action](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-action.md)
- [no-curly-component-invocation](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-curly-component-invocation.md)
- [no-negated-condition](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-negated-condition.md)
- [require-button-type](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-button-type.md)
- [require-valid-alt-text](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-valid-alt-text.md)

### PR DESCRIPTION
**Pull request by neojp**
This PR attempts to close #176 and resolves the following lint errors:

> **eslint-plugin-ember**
> * [no-get](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-get.md)
> * [require-computed-macros](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-computed-macros.md)
> * [use-ember-data-rfc-395-imports](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/use-ember-data-rfc-395-imports.md)
> 
> **ember-template-lint**
> * [link-rel-noopener](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/link-rel-noopener.md)
> * [no-action](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-action.md)
> * [no-curly-component-invocation](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-curly-component-invocation.md)
> * [no-negated-condition](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-negated-condition.md)
> * [require-button-type](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-button-type.md)
> * [require-valid-alt-text](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-valid-alt-text.md)

### CODE REVIEW

File: app/controllers/issues.js [hunk 1]
```diff
@@ -9,17 +10,14 @@ export default Controller.extend({
 
   navLinks: service(),
 
-  queryInput: computed('query', function() {
-    return this.get('query');
-  }),
+  queryInput: computed.reads('query'),
```
Comment (ijlee2) [inline app/controllers/issues.js:13]: A project that I worked on recently, the linter asked me to import `reads` directly from `@ember/object/computed`. I was surprised that this worked without a lint error. (No need to change it. Just an observation.)

File: app/templates/index.hbs [hunk 2]
```diff
@@ -20,7 +20,7 @@
               class="lg:col-3 bg-dark"
               @href="{{repo.htmlUrl}}/issues?q=is%3Aissue+is%3Aopen+label%3A%22Help+Wanted%22+sort%3Acreate-date"
               @title={{repo.displayName}}>
-              <p>Forks: {{#if (not repo.forks)}} No forks {{else}} {{repo.forks}} {{/if}}</p>
+              <p>Forks: {{if repo.forks repo.forks "No forks"}}</p>
```
Comment (ijlee2) [inline app/templates/index.hbs:23]: The line definitely reads nicer. We can assume that GitHub always return a number for `repo.forks` (i.e. not `undefined`) so we could simplify to:

```suggestion
              <p>Forks: {{repo.forks}}</p>
```

**Review by ijlee2 — APPROVED** [review]
Thank you for fixing these lint errors!
